server:
  port: 9100
spring:
  application:
    name: ark-sin
management:
  info:
    git:
      mode: full
  endpoint:
    refresh:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET