server:
  port: 8888
spring:
  application:
    name: settings
  profiles:
    default: native
    group:
      compose: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
