server:
  port: 30309
spring:
  application:
    name: ark-gateway
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://ARK-CORE
          filters:
            - RewritePath=/core/(?<path>.*), /$\{path}
          predicates:
            - Path=/core/**
        - id: consumerModule
          uri: lb://ARK-USER
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
          predicates:
            - Path=/user/**


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

management:
  info:
    git:
      mode: full
  endpoint:
    refresh:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: GET