server:
  port: 80
spring:
  application:
    name: ark-gateway
  cloud:
    gateway:
      routes:
        - id: core
          uri: lb://ARK-CORE
          filters:
            - RewritePath=/core/internal/(?<path>.*), /public/error
            - RewritePath=/core/public/(?<path>.*), /public/$\{path}
            - RewritePath=/core/secured/(?<path>.*), /secured/$\{path}
          predicates:
            - Path=/core/**
        - id: user
          uri: lb://ARK-USER
          filters:
            - RewritePath=/user/internal/(?<path>.*), /public/error
            - RewritePath=/user/public/(?<path>.*), /public/$\{path}
            - RewritePath=/user/secured/(?<path>.*), /secured/$\{path}
          predicates:
            - Path=/user/**
        - id: backup
          uri: lb://ARK-BACKUP
          filters:
            - RewritePath=/backup/internal/(?<path>.*), /public/error
            - RewritePath=/backup/public/(?<path>.*), /public/$\{path}
            - RewritePath=/backup/secured/(?<path>.*), /secured/$\{path}
          predicates:
            - Path=/backup/**


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

management:
  info:
    git:
      mode: full
  endpoint:
    refresh:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: GET