server:
  port: 30301
spring:
  application:
    name: ark-core
elastic-search:
  scheme: http
  hosts: localhost
  ports: 9200
  initial-import:
    enabled: false
management:
  info:
    git:
      mode: full
  endpoint:
    refresh:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET