server:
  port: 30301
spring:
  application:
    name: ark-core
elastic-search:
  scheme: http
  hosts: localhost
  ports: 9200
  initial-import:
    enabled: false

feign:
  client.config.default:
    readTimeout: 15000
    connectTimeout: 15000
    hystrix:
      enabled: false
  user:
    name: user
    url: http://localhost:30302/

management:
  info:
    git:
      mode: full
  endpoint:
    refresh:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET